language: cpp
os: linux
compiler: gcc
sudo: required
dist: trusty

branches:
  only:
    - master

addons:
  apt:
    packages:
      - cmake
      - g++-4.8

before_install:
  # repo for Qt
  - sudo apt-add-repository --yes ppa:beineri/opt-qt487-trusty
  - sudo apt-get -qq update

install:
  - sudo apt-get --yes install qt48base
  - export CXX="g++-4.8"
  - export CC="gcc-4.8"
  
before_script:
  # Qt variables
  - QTDIR="/opt/qt-4.8"
  - PATH="$QTDIR/bin:$PATH"
  - source /opt/qt-4.8/bin/qt-4.8-env.sh

 - make