--- 
addons: 
  apt: 
    packages: 
      - cmake
      - g++-4.8
before_install: 
  - "sudo apt-add-repository --yes ppa:beineri/opt-qt551-trusty"
  - "sudo apt-get -qq update"
before_script: 
  - QTDIR="/opt/qt55"
  - "PATH=\"$QTDIR/bin:$PATH\""
  - "source /opt/qt55/bin/qt55-env.sh"
compiler: 
  - clang
  - gcc
dist: trusty
install: 
  - "sudo apt-get --yes install qt55base"
  - "export CXX=\"g++-4.8\""
  - "export CC=\"gcc-4.8\""
language: cpp
os: linux
script: 
  - qmake "CONFIG+=travis" BatMon.pro
  - make
sudo: required
